### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by siddhantprateek** [The-Origin-Labs/landate#6]
- [ ] Blockchain service _in progress_
- [x] Property Listing Service
- [x] Storage Service
- [x] Document Service _in progress_
- [x] OCR Microservice
- [x] Api Gateway 
- [ ] Notification Service _in progress_
